name: cozy_feels_app
description: "A new Flutter project."
version: 1.0.0+5
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.1.2
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  file_selector: ^1.1.0
  file_selector_android: ^0.5.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/svg/
    - assets/icons/svg/features/
    - assets/icons/svg/feelings/
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle/Dongle-Light.ttf
          weight: 300
        - asset: assets/fonts/Dongle/Dongle-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dongle/Dongle-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/app_icon.png"